import { TemplatePreset, VectorElement } from '../types';

export const TEMPLATE_CATEGORIES = [
  'Tropical',
  'Sunset',
  'Vintage',
  'Neon',
  'Floral',
  'Minimal',
  'Geométrico',
  'Aquarela'
] as const;

export const PRESET_TEMPLATES: TemplatePreset[] = [
  // TROPICAL (6)
  {
    id: 'trop_1',
    title: 'Tucano Tropical Vibrante',
    category: 'Tropical',
    previewUrl: 'https://images.unsplash.com/photo-1550853024-fa5f02be7759?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'el_bg',
        name: 'Fundo Gradiente Sunset',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#0f172a',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'el_img_toucan',
        name: 'Tucano HD Estampa',
        type: 'image',
        x: 140,
        y: 180,
        w: 800,
        h: 750,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: 'transparent',
        stroke: '#00D9FF',
        strokeWidth: 2,
        content: 'https://images.unsplash.com/photo-1550853024-fa5f02be7759?auto=format&fit=crop&w=800&q=80'
      },
      {
        id: 'el_txt_1',
        name: 'Texto Tropical Vibes',
        type: 'text',
        x: 240,
        y: 980,
        w: 600,
        h: 120,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#00D9FF',
        stroke: '#0f172a',
        strokeWidth: 3,
        content: 'TROPICAL PARADISE',
        fontSize: 52,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        textAlign: 'center',
        textWarpStyle: 'arc_upper',
        warpIntensity: 25
      }
    ]
  },
  {
    id: 'trop_2',
    title: 'Folhagem de Costela de Adão',
    category: 'Tropical',
    previewUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'el_bg_2',
        name: 'Fundo Verde Esmeralda',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#022c22',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'el_img_leaves',
        name: 'Costela de Adão Neon',
        type: 'image',
        x: 180,
        y: 150,
        w: 720,
        h: 800,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: 'transparent',
        stroke: '#10B981',
        strokeWidth: 2,
        content: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=800&q=80'
      },
      {
        id: 'el_txt_2',
        name: 'Texto Urban Jungle',
        type: 'text',
        x: 200,
        y: 1020,
        w: 680,
        h: 100,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#34D399',
        stroke: 'transparent',
        strokeWidth: 0,
        content: 'URBAN JUNGLE 2026',
        fontSize: 48,
        fontFamily: 'Impact',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'sun_1',
    title: 'Pôr do Sol Retrô 80s',
    category: 'Sunset',
    previewUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'sun_bg',
        name: 'Fundo Roxo Noturno',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#1e1b4b',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'sun_circle',
        name: 'Sol Gradiente Amarelo',
        type: 'shape',
        shapeType: 'circle',
        x: 290,
        y: 250,
        w: 500,
        h: 500,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#F59E0B',
        stroke: '#EF4444',
        strokeWidth: 6,
        content: ''
      },
      {
        id: 'sun_txt',
        name: 'Texto Summer Vibes',
        type: 'text',
        x: 190,
        y: 850,
        w: 700,
        h: 120,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#F43F5E',
        stroke: '#FFFFFF',
        strokeWidth: 2,
        content: 'ENDLESS SUMMER',
        fontSize: 56,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'vint_1',
    title: 'Selo Vintage Café',
    category: 'Vintage',
    previewUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'vint_bg',
        name: 'Fundo Bege Envelhecido',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#fef3c7',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'vint_border',
        name: 'Borda Oval Vintage',
        type: 'shape',
        shapeType: 'circle',
        x: 190,
        y: 220,
        w: 700,
        h: 700,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: 'transparent',
        stroke: '#78350f',
        strokeWidth: 12,
        content: ''
      },
      {
        id: 'vint_txt',
        name: 'Texto Premium Coffee',
        type: 'text',
        x: 240,
        y: 520,
        w: 600,
        h: 100,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#78350f',
        stroke: 'transparent',
        strokeWidth: 0,
        content: 'PREMIUM COFFEE 1984',
        fontSize: 42,
        fontFamily: 'Georgia',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'neon_1',
    title: 'Cyberpunk Neon Wave',
    category: 'Neon',
    previewUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'neon_bg',
        name: 'Fundo Escuro Cyber',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#090d16',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'neon_star',
        name: 'Estrela Ciano Brilhante',
        type: 'shape',
        shapeType: 'star',
        x: 340,
        y: 280,
        w: 400,
        h: 400,
        rotation: 15,
        visible: true,
        locked: false,
        opacity: 100,
        fill: 'transparent',
        stroke: '#00D9FF',
        strokeWidth: 8,
        content: ''
      },
      {
        id: 'neon_txt',
        name: 'Texto Cyberpunk 2026',
        type: 'text',
        x: 190,
        y: 820,
        w: 700,
        h: 120,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#EC4899',
        stroke: '#00D9FF',
        strokeWidth: 2,
        content: 'NEON WAVE 2026',
        fontSize: 54,
        fontFamily: 'Impact',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'flor_1',
    title: 'Buquê Floral Aquarela',
    category: 'Floral',
    previewUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=600&q=80',
    elements: [
      {
        id: 'flor_bg',
        name: 'Fundo Rosa Claro',
        type: 'shape',
        shapeType: 'rectangle',
        x: 0,
        y: 0,
        w: 1080,
        h: 1350,
        rotation: 0,
        visible: true,
        locked: true,
        opacity: 100,
        fill: '#fdf2f8',
        stroke: 'transparent',
        strokeWidth: 0,
        content: ''
      },
      {
        id: 'flor_img',
        name: 'Flores Aquarela',
        type: 'image',
        x: 190,
        y: 180,
        w: 700,
        h: 700,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: 'transparent',
        stroke: 'transparent',
        strokeWidth: 0,
        content: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80'
      },
      {
        id: 'flor_txt',
        name: 'Texto Gratidão',
        type: 'text',
        x: 240,
        y: 950,
        w: 600,
        h: 100,
        rotation: 0,
        visible: true,
        locked: false,
        opacity: 100,
        fill: '#be185d',
        stroke: 'transparent',
        strokeWidth: 0,
        content: 'Com Amor & Gratidão',
        fontSize: 46,
        fontFamily: 'Georgia',
        textAlign: 'center'
      }
    ]
  }
];
